### ISSUE TITLE
Email?

### ISSUE THREAD

**Issue by anonymous-repo-tech** [atozto9/algorithm#1]
Hi @atozto9 ,

Because there is no way to contact you except git hub issue, I had no choice to create this issue.

Currently, I encounter a confidential problem which is somehow related with you, so I want to talk with you, in private.
May I ask your email? or if your email is nouvemps@gmail.com, could you check your email?

Sorry for alarming you with an issue unrelated to this repo.

**Comment by atozto9** [comment]
Hi @anonymous-repo-tech 

Sorry for the late reply
I checked an email

Thanks

**Comment by anonymous-repo-tech** [comment]
Thank you so much!
